### ISSUE TITLE
CONTACT US APP / EMULATOR - Background image

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/contactUsPlugin#60]
The background image should zoom in/out to fit the height or width of the entire screen (whichever is lesser so there is no white/blank space) and stay fixed.

**Comment by kmtabish** [comment]
Updated the plugin. Should be working now. please review.

**Comment by nathankeating** [comment]
@kmtabish Here are some screen shots of what I am still encountering:

Layout 1:
<img width="403" alt="screen shot 2015-09-21 at 12 15 37 pm" src="https://cloud.githubusercontent.com/assets/6145369/10002183/8eca710c-605a-11e5-899c-dbbcc8eb681d.png">

Layout 2:
<img width="398" alt="screen shot 2015-09-21 at 12 15 41 pm" src="https://cloud.githubusercontent.com/assets/6145369/10002184/9301cbd0-605a-11e5-91b3-b8be1e39617b.png">

**Comment by sakshityagi** [comment]
Tested again. Working fine on my end. Please let me know if its still an issue.

**Comment by ianblair44** [comment]
@nathankeating

**Comment by nathankeating** [comment]
It now zooms to fit the screen but does not stay fixed. I am using an iPhone 6.

Please test on the device.

**Comment by ianblair44** [comment]
@nathankeating these need to be logged in the customer service tickets repo. 

John and India need to sync up regarding the background image staying in the same place. It's affecting all plugins.

**Comment by nathankeating** [comment]
I'm moving over the tickets. All of these are from the previous method of logging tickets

**Comment by nathankeating** [comment]
moved to https://github.com/BuildFire/customerServiceTickets/issues/740
